name: Foundry SharePoint Knowledge Infrastructure Deployment
run-name: Foundry SharePoint Knowledge Infrastructure Deployment [${{ inputs.target-environment || github.run_id }}]

on: 
  workflow_dispatch:
    inputs:      
      target-environment:              
        type: choice
        default: Dev
        required: true
        description: The target Azure resource group.
        options:
          - Dev
          - UAT
          - Prod 
      resource-group-name-prefix:
        required: true
        default: <your azure resource group prefix>
        description: The prefix for all Azure resource group names.
      deployment-entra-enterprise-app-object-id:
        required: true
        default: <your entra id infrastructure app object id>
        description: The object id of the Entra Enterprise App used to provision PaaS and other Azure infrastructure.
      root-domain:
        required: true
        default: <your root domain>
        description: The root domain of the production web app.
      sub-domain:
        required: true
        default: <your sub domain>
        description: The sub domain of the production web app; the public URL will be https://[sub-domain].[root-domain]
      primary-region:
        required: true
        default: northcentralus
        description: The main Azure region used for PaaS components.
      secondary-region:
        required: true
        default: eastus2
        description: The fallback Azure region used for PaaS components that do not support the primary region.     
      owner-email:
        required: false
        default: <your admin email address>
        description: An administrator email address who will be granted owner access to key vault and entra id apps.     
      localhost-url:
        required: false
        default: <your front end dev URL>
        description: The team local development environment URL for which CORS rules will be enabled in lower environments.
      foundry-sku:
        default: S0
        required: true
        description: The SKU of the Microsoft Foundry resource.
      
      #TODO: add these back in if GitHub ever allows more than 10 inputs...          
      #llm-model:
      #  required: true
      #  default: "gpt-4.1"
      #  description: The type of LLM AI model to use.      
      #llm-capacity:
      #  required: true
      #  default: "501"
      #  description: The LLM capacity (in units of 100,000 tokens per minute).      
      #llm-version:
      #  required: true
      #  default: "2025-04-14"
      #  description: The LLM Azure Foundry API version.      
      #embedding-model:
      #  required: true
      #  default: "text-embedding-3-small"
      #  description: The type of text embeddings AI model to use.      
      #embedding-capacity:
      #  required: true
      #  default: "511"
      #  description: The text embeddings capacity (in units of 100,000 tokens per minute).      
      #embedding-version:
      #  required: true
      #  default: "1"
      #  description: The text embeddings Azure Foundry API version.
      #image-model:
      #  required: true
      #  default: "embed-v-4-0"
      #  description: The type of image embeddings AI model to use.      
      #image-capacity:
      #  default: "5"
      #  required: true
      #  description: The image embeddings capacity (in units of 100,000 tokens per minute).      
      #image-version:
      #  required: true
      #  default: "1"
      #  description: The image embeddings Azure Foundry API version.
env:
  SCRIPT_FILE_NAME: infrastructure.sh
  INFRASTRUCTURE_WORKING_DIRECTORY: deployment

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    name: Infrastructure Deployment Job
    runs-on: ubuntu-latest
    defaults:
      run:        
        working-directory: ./${{ env.INFRASTRUCTURE_WORKING_DIRECTORY }}
    steps:  
      - name: Checkout Branch
        uses: actions/checkout@v4 
        
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_DEPLOYMENT_CREDS }}
      
      - name: Deploy Resource Group
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            #initialization
            chmod +x $GITHUB_WORKSPACE/${{ env.INFRASTRUCTURE_WORKING_DIRECTORY }}/${{ env.SCRIPT_FILE_NAME }};

            #return
            $GITHUB_WORKSPACE/${{ env.INFRASTRUCTURE_WORKING_DIRECTORY }}/${{ env.SCRIPT_FILE_NAME }} \
              "${{ github.event.inputs.target-environment }}" \
              "${{ github.event.inputs.resource-group-name-prefix }}" \
              "${{ github.event.inputs.deployment-entra-enterprise-app-object-id }}" \
              "${{ github.event.inputs.root-domain }}" \
              "${{ github.event.inputs.sub-domain }}" \
              "${{ github.event.inputs.primary-region }}" \
              "${{ github.event.inputs.secondary-region }}" \
              "${{ github.event.inputs.owner-email }}" \
              "${{ github.event.inputs.localhost-url }}" \
              "${{ github.event.inputs.foundry-sku }}" \
              "${{ secrets.SHAREPOINT_WEBHOOK_SECRET }}"; 

              #TODO: add these back in if GitHub ever allows more than 10 inputs...             
              #"${{ github.event.inputs.llm-model }}" \
              #"${{ github.event.inputs.llm-capacity }}" \
              #"${{ github.event.inputs.llm-version }}" \
              #"${{ github.event.inputs.embedding-model }}" \
              #"${{ github.event.inputs.embedding-capacity }}" \
              #"${{ github.event.inputs.embedding-version }}" \
              #"${{ github.event.inputs.image-model }}" \
              #"${{ github.event.inputs.image-capacity }}" \
              #"${{ github.event.inputs.image-version }}";
